1. Why does the program print the two lines below?
(2) Exception occurred
(2) in finally clause

A. count is two so catch(){} is executed.
   finally(){} is always executed end of the while statement.



2. Why does the program print the line below (It looks like the program does not print the line because
of the break statement)?
(3) in finally clause

A. finally(){} is always executed with or without exceptions



3. Why does the program print the line beloww
Main program ends

A  System.out.println("Main program ends"); is outside the while statement.